// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_score from "./routes/api/score.ts";
import * as $ext_username_ from "./routes/ext/[username].tsx";
import * as $iframe_chrome_ext from "./routes/iframe/chrome-ext.tsx";
import * as $iframe_credit_score from "./routes/iframe/credit-score.tsx";
import * as $iframe_insurance_fee_calculator from "./routes/iframe/insurance-fee-calculator.tsx";
import * as $index from "./routes/index.tsx";
import * as $insurance from "./routes/insurance.tsx";
import * as $test from "./routes/test.tsx";
import * as $u_username_ from "./routes/u/[username].tsx";
import * as $Button from "./islands/Button.tsx";
import * as $CoverageResult from "./islands/CoverageResult.tsx";
import * as $CreditScore from "./islands/CreditScore.tsx";
import * as $CreditScoreChExt from "./islands/CreditScoreChExt.tsx";
import * as $InsuranceCalc from "./islands/InsuranceCalc.tsx";
import * as $MenuBar from "./islands/MenuBar.tsx";
import * as $PasswordGate from "./islands/PasswordGate.tsx";
import * as $ScoreResult from "./islands/ScoreResult.tsx";
import * as $ScoreResultsChExt from "./islands/ScoreResultsChExt.tsx";
import * as $test_1 from "./islands/test.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/score.ts": $api_score,
    "./routes/ext/[username].tsx": $ext_username_,
    "./routes/iframe/chrome-ext.tsx": $iframe_chrome_ext,
    "./routes/iframe/credit-score.tsx": $iframe_credit_score,
    "./routes/iframe/insurance-fee-calculator.tsx":
      $iframe_insurance_fee_calculator,
    "./routes/index.tsx": $index,
    "./routes/insurance.tsx": $insurance,
    "./routes/test.tsx": $test,
    "./routes/u/[username].tsx": $u_username_,
  },
  islands: {
    "./islands/Button.tsx": $Button,
    "./islands/CoverageResult.tsx": $CoverageResult,
    "./islands/CreditScore.tsx": $CreditScore,
    "./islands/CreditScoreChExt.tsx": $CreditScoreChExt,
    "./islands/InsuranceCalc.tsx": $InsuranceCalc,
    "./islands/MenuBar.tsx": $MenuBar,
    "./islands/PasswordGate.tsx": $PasswordGate,
    "./islands/ScoreResult.tsx": $ScoreResult,
    "./islands/ScoreResultsChExt.tsx": $ScoreResultsChExt,
    "./islands/test.tsx": $test_1,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
